// Standard filter options for the developer feed

export const SPECIALIZATION_OPTIONS = [
  "Software Enginner",
  "Software Development Engineer (SDE)",
  "Web Developer",
  "Frontend Developer",
  "Backend Developer",
  "Fullstack Developer",
  "DevOps Engineer",
  "AI / ML Engineer",
  "Mobile App Developer (IOS / Android)",
  "Android Developer",
  "IOS Developer",
  "Data Scientist / Engineer",
  "Game Developer",
  "Cloud Architect",
  "Cybersecurity Engineer",
  "UI / UX Designer",
  "Blockchain Developer",
];

export const SKILL_OPTIONS = [
  "Frontend",
  "Backend",
  "Databases",
  "DevOps",
  "Deployment",
  "AI",
  "ML",
  "GenAI",
  "Vibe Coding",
  "Claude",
  "Codex",
  "React",
  "Node.js",
  "Express.js",
  "Next.js",
  "Svelte",
  "Vue.js",
  "Angular",
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C++",
  "C",
  "C#",
  "Go",
  "Rust",
  "Docker",
  "Kubernetes",
  "AWS",
  "MongoDB",
  "PostgreSQL",
  "SQL",
  "MySQL",
  "Redis",
  "GraphQL",
  "HTML",
  "CSS",
  "SCSS",
  "SASS",
  "Tailwind CSS",
  "PyTorch",
  "TensorFlow",
];

export const EXPERIENCE_OPTIONS = [
  { label: "Freshers (0 - 1 years)", min: 0, max: 1 },
  { label: "Junior (1 - 3 years)", min: 1, max: 3 },
  { label: "Mid-Level (3 - 5 years)", min: 3, max: 5 },
  { label: "Senior (5 - 8 years)", min: 5, max: 8 },
  { label: "Lead / Principal (8+ years)", min: 8, max: 50 },
];

export const EMPLOYMENT_STATUS_OPTIONS = [
  { label: "Employed", value: "employed" },
  { label: "Self-Employed", value: "self-employed" },
  { label: "Freelancing", value: "freelance" },
  { label: "Student", value: "student" },
  { label: "Hobbyist", value: "hobbyist" },
];

export const POPULAR_LOCATIONS = [
  "Mumbai, India",
  "Bengaluru, India",
  "Delhi / NCR, India",
  "San Francisco, USA",
  "New York, USA",
  "London, UK",
  "Berlin, Germany",
  "Toronto, Canada",
  "Singapore",
  "Remote",
];
